#!/usr/bin/env bash

set -Eeuo pipefail

# Number of HTTP requests generated by this test.
REQUEST_COUNT="${REQUEST_COUNT:-300}"

# Maximum number of simultaneously running curl processes.
CONCURRENCY="${CONCURRENCY:-10}"

# Artificial endpoint latency in milliseconds.
DELAY_MS="${DELAY_MS:-200}"

# JWT must be passed through the environment:
# export TOKEN="..."
if [[ -z "${TOKEN:-}" ]]; then
    echo "TOKEN environment variable is not set." >&2
    echo 'Run: export TOKEN="<your-jwt>"' >&2
    exit 1
fi

URL="http://localhost:8081/internal/load-test/http?delayMilliseconds=${DELAY_MS}"

echo "Starting HTTP load test"
echo "Requests:    ${REQUEST_COUNT}"
echo "Concurrency: ${CONCURRENCY}"
echo "Delay:       ${DELAY_MS} ms"
echo

seq 1 "${REQUEST_COUNT}" |
    xargs -P "${CONCURRENCY}" -I {} \
        curl \
            --silent \
            --output /dev/null \
            --write-out "status=%{http_code} time=%{time_total}\n" \
            --header "Authorization: Bearer ${TOKEN}" \
            "${URL}"