{{- if .Values.routes.enabled }}
{{- if and .Values.components.paymentService.enabled (or (eq .Values.renderScope "all") (eq .Values.renderScope "paymentService")) }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: payment-service
  labels:
    {{- include "resilient-orders.componentLabels" (dict "root" . "name" "payment-service" "component" "backend") | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.routes.gatewayName | quote }}
      namespace: {{ .Values.routes.gatewayNamespace | quote }}
  hostnames:
    - {{ .Values.routes.hosts.paymentService | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: payment-service
          port: {{ .Values.components.paymentService.port }}
---
{{- end }}
{{- if and .Values.components.orderService.enabled (or (eq .Values.renderScope "all") (eq .Values.renderScope "orderService")) }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: order-service
  labels:
    {{- include "resilient-orders.componentLabels" (dict "root" . "name" "order-service" "component" "backend") | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.routes.gatewayName | quote }}
      namespace: {{ .Values.routes.gatewayNamespace | quote }}
  hostnames:
    - {{ .Values.routes.hosts.orderService | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: order-service
          port: {{ .Values.components.orderService.port }}
---
{{- end }}
{{- if and .Values.components.notificationService.enabled (or (eq .Values.renderScope "all") (eq .Values.renderScope "notificationService")) }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: notification-service
  labels:
    {{- include "resilient-orders.componentLabels" (dict "root" . "name" "notification-service" "component" "backend") | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.routes.gatewayName | quote }}
      namespace: {{ .Values.routes.gatewayNamespace | quote }}
  hostnames:
    - {{ .Values.routes.hosts.notificationService | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: notification-service
          port: {{ .Values.components.notificationService.port }}
{{- end }}
{{- end }}
