server:
  port: 8082

logging:
  structured:
    format:
      console: logstash
    json:
      add:
        service: ${spring.application.name}
  pattern:
    level: "%5p [traceId=%X{traceId:-}, spanId=%X{spanId:-}]"

spring:
  application:
    name: payment-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics