server:
  port: 8082

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"

spring:
  application:
    name: payment-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics