apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-workload
  labels:
    {{- include "resilient-orders.componentLabels" (dict "root" . "name" "platform-workload" "component" "platform") | nindent 4 }}
automountServiceAccountToken: false
