{{- if and .Values.gateway.enabled .Values.gateway.routes.vault.enabled .Values.components.vault.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vault-ui
  namespace: {{ .Values.namespaces.platform | quote }}
  labels:
    {{- include "resilient-orders.componentLabels" (dict "root" . "name" "vault" "component" "secrets") | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name | quote }}
      namespace: {{ .Values.namespaces.platform | quote }}
  hostnames:
    - {{ .Values.gateway.hosts.vault | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: vault
          port: 8200
{{- end }}
{{- if and .Values.gateway.enabled .Values.gateway.routes.argocd.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-ui
  namespace: argocd
  labels:
    {{- include "resilient-orders.componentLabels" (dict "root" . "name" "argocd" "component" "gitops") | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name | quote }}
      namespace: {{ .Values.namespaces.platform | quote }}
  hostnames:
    - {{ .Values.gateway.hosts.argocd | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: argo-cd-argocd-server
          port: 80
{{- end }}
