server:
  port: 8081

logging:
  structured:
    format:
      console: logstash
    json:
      add:
        service: ${spring.application.name}
  pattern:
    level: "%5p [traceId=%X{traceId:-}, spanId=%X{spanId:-}]"

resilience4j:
  bulkhead:
    instances:
      exportJobBulkhead:
        max-concurrent-calls: 2 # одновременно максимум 2 export jobs
        max-wait-duration: 0 # третий job не ждёт, а сразу получает ошибку
  retry:
    instances:
      paymentServiceRetry:
        max-attempts: 3
        wait-duration: 500ms
  circuitbreaker:
    instances:
      paymentServiceCircuitBreaker:
        sliding-window-size: 5 # Circuit Breaker смотрит последние 5 вызовов.
        minimum-number-of-calls: 3 # Если после минимум 3 вызовов
        failure-rate-threshold: 50 # процент ошибок >= 50%, он переходит в OPEN.
        wait-duration-in-open-state: 10s

app:
  payment-client:
    type: feign
  outbox:
    publisher:
      fixed-delay-ms: 5000

security:
  jwt:
    secret: "dev-secret-key-dev-secret-key-123456"

spring:
  application:
    name: order-service
  cloud:
    openfeign:
      client:
        config:
          payment-service:
            connectTimeout: 1000
            readTimeout: 2000
  kafka:
    template:
      observation-enabled: true
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8085
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all # broker ждёт подтверждение от replicas
      retries: 3 # producer повторит отправку при временной ошибке
      properties:
        enable.idempotence: true # защита от duplicate при retry producer'а
        spring.json.add.type.headers: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated # RabbitMQ подтвердит, что broker принял message.
    publisher-returns: true # если message не смог попасть ни в одну queue, broker вернёт его producer’у.
    template:
      mandatory: true # требовать return для unroutable messages.
      observation-enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 180s
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: orders_user
    password: orders_pass
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: OrderServiceHikariPool
      maximum-pool-size: 2 # Максимум 2 соединения к БД одновременно.
      minimum-idle: 1 # Hikari старается держать хотя бы 1 свободное соединение готовым.
      connection-timeout: 3000 # Если все 2 соединения заняты, новый request ждёт максимум 3 секунды. Потом ошибка.
      idle-timeout: 600000 # Свободное соединение может простаивать 10 минут, потом Hikari может его закрыть.
      max-lifetime: 1800000 # Соединение живёт максимум 30 минут, потом пересоздаётся. Это защищает от старых/stale connections.

  jpa:
    open-in-view: false # Когда включено соединение держится принудительно на все время http запроса
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

services:
  payment:
    base-url: http://localhost:8082
    connect-timeout-ms: 1000
    read-timeout-ms: 2000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  tracing:
    sampling:
      probability: 1.0 # локально отправляем 100% traces
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces # отправляем traces в Jaeger через OTLP HTTP