server:
  port: 8081

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"

resilience4j:
  retry:
    instances:
      paymentServiceRetry:
        max-attempts: 3
        wait-duration: 500ms
  circuitbreaker:
    instances:
      paymentServiceCircuitBreaker:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

app:
  payment-client:
    type: feign

spring:
  application:
    name: order-service
  cloud:
    openfeign:
      client:
        config:
          payment-service:
            connectTimeout: 1000
            readTimeout: 2000
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: orders_user
    password: orders_pass
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: OrderServiceHikariPool
      maximum-pool-size: 2 # Максимум 2 соединения к БД одновременно.
      minimum-idle: 1 # Hikari старается держать хотя бы 1 свободное соединение готовым.
      connection-timeout: 3000 # Если все 5 соединений заняты, новый request ждёт максимум 3 секунды. Потом ошибка.
      idle-timeout: 600000 # Свободное соединение может простаивать 10 минут, потом Hikari может его закрыть.
      max-lifetime: 1800000 # Соединение живёт максимум 30 минут, потом пересоздаётся. Это защищает от старых/stale connections.

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

services:
  payment:
    base-url: http://localhost:8082
    connect-timeout-ms: 1000
    read-timeout-ms: 2000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics