#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-SQL
  CREATE ROLE "$POSTGRES_EXPORTER_USER" WITH LOGIN PASSWORD '$POSTGRES_EXPORTER_PASSWORD';
  GRANT pg_monitor TO "$POSTGRES_EXPORTER_USER";
  CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
SQL
