{{- if .Values.components.paymentService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    {{- include "resilient-orders.componentLabels" (dict "root" . "name" "payment-service" "component" "backend") | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.components.paymentService.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: payment-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    {{- include "resilient-orders.componentLabels" (dict "root" . "name" "payment-service" "component" "backend") | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: payment-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: payment-service
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: {{ .Values.labels.partOf | quote }}
    spec:
      serviceAccountName: app-workload
      automountServiceAccountToken: false
      enableServiceLinks: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: payment-service
          image: {{ .Values.components.paymentService.image | quote }}
          imagePullPolicy: {{ .Values.components.paymentService.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.components.paymentService.port }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.components.paymentService.javaToolOptions | quote }}
            - name: SERVER_PORT
              value: {{ .Values.components.paymentService.port | quote }}
            - name: SPRING_CLOUD_VAULT_ENABLED
              value: "false"
            - name: MANAGEMENT_HEALTH_VAULT_ENABLED
              value: "false"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 60
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 300
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 10
          startupProbe:
            tcpSocket:
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 90
          resources:
            {{- toYaml .Values.components.paymentService.resources | nindent 12 }}
{{- end }}
