apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-workload
  labels:
    {{- include "resilient-orders.componentLabels" (dict "root" . "name" "app-workload" "component" "backend") | nindent 4 }}
automountServiceAccountToken: false
