# Prometheus server configuration.

global:
  # Как часто Prometheus будет запрашивать метрики у targets.
  scrape_interval: 15s

  # Как часто Prometheus пересчитывает alerting/recording rules.
  evaluation_interval: 15s

scrape_configs:
  # Название группы targets.
  # Оно появится как label job="order-service".
  - job_name: "postgresql"

    static_configs:
      - targets:
          # Prometheus работает внутри Docker network,
          # поэтому обращается по compose service name,
          # а не через localhost.
          - "postgres-exporter:9187"

  - job_name: "order-service"

    # Spring Boot Prometheus endpoint.
    metrics_path: "/actuator/prometheus"

    static_configs:
      - targets:
          # Prometheus работает внутри Docker network,
          # поэтому обращается по compose service name,
          # а не через localhost.
          - "order-service:8081"

  - job_name: "payment-service"

    metrics_path: "/actuator/prometheus"

    static_configs:
      - targets:
          - "payment-service:8082"

  - job_name: "notification-service"

    metrics_path: "/actuator/prometheus"

    static_configs:
      - targets:
          - "notification-service:8083"