server:
  port: 8083

logging:
  structured:
    format:
      console: logstash
    json:
      add:
        service: ${spring.application.name}
  pattern:
    level: "%5p [traceId=%X{traceId:-}, spanId=%X{spanId:-}]"

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8085
    listener:
      ack-mode: manual
      observation-enabled: true
    producer: # notification-service не только consumer, но и producer в DLT. А producer по умолчанию пытается отправить value как String
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: notification-service # имя consumer group. Kafka хранит offset отдельно для этой группы.
      auto-offset-reset: earliest # если у группы ещё нет offset, читать с начала topic.
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.use.type.header: false
        spring.json.trusted.packages: "com.example.notificationservice.dto,com.example.orderservice.dto"
        spring.json.value.default.type: com.example.notificationservice.dto.OrderCreatedMessage

  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: orders_user
    password: orders_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false # Когда включено соединение держится принудительно на все время http запроса
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    listener:
      simple:
        observation-enabled: true
        acknowledge-mode: manual # (auto) Spring сам подтвердит сообщение, если метод успешно завершился.
        default-requeue-rejected: false # Если listener выбросил exception, сообщение НЕ возвращается бесконечно в ту же очередь, а уходит в DLQ, если DLQ настроена.
        retry:
          enabled: false
          max-attempts: 3 # попробовать обработать сообщение 3 раза
          initial-interval: 1000 # пауза 1 секунда
          multiplier: 2 # потом 2 секунды
          max-interval: 5000 # потом максимум 5 секунд, если всё равно ошибка → reject → DLQ

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  tracing:
    sampling:
      probability: 1.0 # локально отправляем 100% traces
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces # отправляем traces в Jaeger через OTLP HTTP
