server:
  port: 8083

logging:
  structured:
    format:
      console: logstash
    json:
      add:
        service: ${spring.application.name}
  pattern:
    level: "%5p [traceId=%X{traceId:-}, spanId=%X{spanId:-}]"

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8085
    listener:
      ack-mode: manual
      observation-enabled: true
    producer: # notification-service не только consumer, но и producer в DLT. А producer по умолчанию пытается отправить value как String
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: notification-service # имя consumer group. Kafka хранит offset отдельно для этой группы.
      auto-offset-reset: earliest # если у группы ещё нет offset, читать с начала topic.
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.use.type.header: false
        spring.json.trusted.packages: "com.example.notificationservice.dto,com.example.orderservice.dto"
        spring.json.value.default.type: com.example.notificationservice.dto.OrderCreatedMessage

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}?currentSchema=notification_service
    username: ${NOTIFICATION_SERVICE_DB_USER}
    password: ${NOTIFICATION_SERVICE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false # Когда включено соединение держится принудительно на все время http запроса
    properties:
      hibernate:
        # Hibernate только валидирует модель против schema notification_service.
        # DDL управляется Flyway-миграциями.
        default_schema: notification_service
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration
    # Единственная schema в списке становится default schema Flyway.
    # Поэтому migration SQL не нужно засорять префиксом notification_service.
    schemas: notification_service
    user: ${NOTIFICATION_SERVICE_DB_OWNER_USER}
    password: ${NOTIFICATION_SERVICE_DB_OWNER_PASSWORD}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

    listener:
      simple:
        observation-enabled: true
        acknowledge-mode: manual # (auto) Spring сам подтвердит сообщение, если метод успешно завершился.
        default-requeue-rejected: false # Если listener выбросил exception, сообщение НЕ возвращается бесконечно в ту же очередь, а уходит в DLQ, если DLQ настроена.
        retry:
          enabled: false
          max-attempts: 3 # попробовать обработать сообщение 3 раза
          initial-interval: 1000 # пауза 1 секунда
          multiplier: 2 # потом 2 секунды
          max-interval: 5000 # потом максимум 5 секунд, если всё равно ошибка → reject → DLQ

management:
  metrics:
    distribution:
      percentiles-histogram:
        # Включает histogram buckets для всех HTTP server timers.
        # Благодаря этому Prometheus сможет считать p95/p99 через
        # histogram_quantile(), в том числе после масштабирования сервиса.
        http.server.requests: true

      minimum-expected-value:
        # Нижняя ожидаемая граница HTTP latency.
        # Помогает Micrometer не создавать ненужные buckets ниже 5 ms.
        http.server.requests: 5ms

      maximum-expected-value:
        # Верхняя ожидаемая граница.
        # запросы дольше всё равно попадут в +Inf bucket.
        http.server.requests: 10s
  endpoints:
    web:
      exposure:
        # health нужен для проверки состояния,
        # prometheus — для scrape Prometheus server.
        include: health,prometheus
  endpoint:
    health:
      # Позже здесь увидим состояние DB, Redis, RabbitMQ и Kafka,
      # если соответствующие health indicators доступны.
      show-details: when-authorized
  tracing:
    sampling:
      probability: 1.0 # локально отправляем 100% traces
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces # отправляем traces в Jaeger через OTLP HTTP
